const Head = () => {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content="#F1F2F6" />
      <link rel="manifest" href="/manifest.json" />
      <link rel="apple-touch-icon" href="/icon-192x192.png" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}

export default Head
